[package]
name = "websocket-sigma-implementation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha1_smol ="1.0.0"
base64 = "0.20.0"
tokio = { version = "1", features = ["full"] }